AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
  RunRailsCops: true

Style/Documentation:
  Enabled: false
