db:
  image: postgres
executor:
  build: ./app/executor
  links:
    - db
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
web:
  build: .
  command: bin/run
  volumes:
    - .:/e-800
  ports:
    - "3000:3000"
  links:
    - db
