db:
  build: ./db
  dockerfile: db.Dockerfile
web:
  build: .
  command: sh -c "sleep 10 && rm -f /opt/e-800/tmp/pids/server.pid && /opt/e-800/bin/rake db:migrate && /opt/e-800/bin/rails s -p 3000 -b '0.0.0.0'"
  volumes:
    - .:/opt/e-800
    - /var/run/docker.sock:/var/run/docker.sock
  ports:
    - "3000:3000"
  links:
    - db
