db:
  image: postgres
executor:
  build: ./app/executor
  links:
    - db
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
web:
  build: .
  command: sh -c "sleep 10 && /e-800/bin/rake db:migrate && /e-800/bin/rails s -p 3000 -b '0.0.0.0'"
  volumes:
    - .:/e-800
  ports:
    - "3000:3000"
  links:
    - db
