db:
  image: postgres
executor:
  build: ./app/executor
  links:
    - db
web:
  build: .
  command: bin/rails s -p 3000 -b '0.0.0.0'
  volumes:
    - .:/e-800
  ports:
    - "3000:3000"
  links:
    - db
